---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fhvmknhq/repositories/belajar-laravel
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH
    - $DEPLOYPATH/artisan config:clear
    - $DEPLOYPATH/artisan cache:clear
    - $DEPLOYPATH/artisan view:clear  
    
