---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fhvmknhq/belajar-laravel
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH
    - cp -rf $DEPLOYPATH/public/css /home/fhvmknhq/public_html/
    - cp -rf $DEPLOYPATH/public/images /home/fhvmknhq/public_html/
    - $DEPLOYPATH/artisan config:cache
    - $DEPLOYPATH/artisan route:cache
    - $DEPLOYPATH/artisan view:cache
